---
title: "R Notebook"
output: html_notebook
---

```{r}
#load libraries
library("dplyr")
library("readr")
library("ggplot2")
```

```{r}
#read data
country_wise <- read.csv("country-wise-average.csv")
```
```{r}
#inspect data
head(country_wise)
```
```{r}
#visualizing wasting against population
wasting_viz <- ggplot(country_wise,aes(x = Income.Classification,y =Wasting)) + geom_bar(stat = "identity",aes(color = U5.Population...000s.),fill = "darkblue") + labs(title = "Wasting by Income Classification")
wasting_viz
```

```{r}
#visualizing stunting growth
stunting_vis <- ggplot(country_wise,aes(x = Income.Classification,y = Stunting )) + geom_bar(stat = "identity",aes(color = U5.Population...000s. ),fill = "darkblue")  + labs(title = "Stunting")
stunting_vis
```
```{r}
overweight_vis <- ggplot(country_wise,aes(x = Income.Classification,y = Overweight )) + geom_bar(stat = "identity",aes(color = U5.Population...000s. ),fill = "darkblue")  + labs(title = "Overweight")
overweight_vis

```





